name: Deploy

on:
  push:
    branches:
      - main

jobs:
  ios_build:
    name: Build iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install gpg
        run: brew install gnupg
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
          IOS_P12_PASSWORD: ${{ secrets.IOS_P12_PASSWORD }}
        run: ./.github/scripts/iOS/decrypt-secrets.sh
      - name: Archiving project
        run: ./.github/scripts/iOS/archive-app.sh
      - name: Exporting .ipa
        run: ./.github/scripts/iOS/export-ipa.sh
      - name: Move to static folder
        run: |
          mkdir -p 'web/public/apps/iOS'
          mv 'build/iOS/RSS App.ipa' 'web/public/apps/iOS/RSS App.ipa'

