name: Deploy

on:
  push:
    branches:
      - main

jobs:
  ios_build:
    name: Build iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build iOS app into IPA
        uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: iOS/RSS App.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          certificate-password: ${{ secrets.P12_PASSWORD }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          workspace-path: iOS/RSS App.xcworkspace
          scheme: RSS App
          export-method: ad-hoc
          export-options: iOS/exportOptions.plist
      - name: Move to static folder
        run: |
          mkdir -p 'web/public/apps/iOS'
          mv 'build/iOS/RSS App.ipa' 'web/public/apps/iOS/RSS App.ipa'

